default:
  just --list
run part day=`date +%d` *args="":
  cargo run -p day-{{day}} --bin part{{part}} {{args}}
test part="" day=`date +%d` *args="":
  cargo test -p day-{{day}} {{part}} {{args}}
create name=`date +day-%d`:
  cargo generate --path ./template --name {{name}}
load day=`date +%-d` dir="$dir":
    #!/usr/bin/env bash
    set -euxo pipefail
    dir=$(printf "day-%02d" {{day}})
    source ~/.bash_aliases
    aoc-load 2023 {{day}} {{dir}}/inputs/input.txt
